### ISSUE TITLE
[feature] dependencies on other programs

### ISSUE THREAD

**Issue by nhomble** [basherpm/basher#104]
Hello! I'm wondering if there's been any thoughts around declaring and verifying shell dependencies during installation.

An example I had today: I did a basher install but then I noticed `jq` was missing.

Maybe there could be a known file in the basher directory structure such that basher could check against `$PATH`.

Eventually, we could hook into other managers for complicated installs. Maybe declare other basher dependencies but maybe brew as well?

**Comment by juanibiapina** [comment]
I haven't really thought about this.

From the top of my head, one easy thing to do is to specify a list of binaries which are required in `package.sh`. So if you specify `jq`, install could fail if `jq` is not present, independent of where it comes from. Again this is just from the top of my head and I haven't thought this through.

**Comment by nhomble** [comment]
That would certainly block bad installs, but it would be cooler if basher could install the dependency for me.

**Comment by pawamoy** [comment]
So you want a Bash package manager to install non-Bash packages :smile: ?

**Comment by nhomble** [comment]
> Bash package manager to install non-Bash packages

Nah not necessarily, I am just thinking that whatever requirements file is proposed may not have to assume these are only basher installed. Could just be verifying it is on `$PATH` which was @juanibiapina earlier point.

> dozens of other package managers

The file could list of basher specific dependencies that follow the `<org>/<repo>/` format, but I was thinking we could come up with a scheme to allow for extension later on like `basher://<org>/<repo>` or `basher://bitbucket.org/user/repo_name`. 

But hey, if we just wanna run with the `package.sh` idea, that's a good start too.

**Comment by pawamoy** [comment]
By the way you might be interested in https://github.com/kdeldycke/meta-package-manager :stuck_out_tongue:

**Comment by nhomble** [comment]
Thanks @pawamoy I didn't know and I will look at that now! 

@juanibiapina I should be good on this feature for now, so I'll close it.
