### ISSUE TITLE
check manpages after upgrade

### ISSUE THREAD

**Issue by nhomble** [basherpm/basher#105]
To pull in some new manpages, I had to `uninstall` and `install` a basher package. I was expecting `basher upgrade <package>` to be check for a new `man/` dir after `upgrade`. 

More generally, I see in the install script, there is a lot of linkage done after cloning the repository. **Assuming** the linking is idempotent, should we do this similar linkage at the end of the `upgrade` step?

**Comment by juanibiapina** [comment]
Yeah, currently upgrading is not working well in these cases. I think it makes sense that upgrading should work as if installing the package in the first place. But it also needs to "uninstall" before doing that to remove for instance dangling symlinks to files the were removed.

So one way to solve it could be to run all uninstall steps except actually removing the code, then pulling the code, then running all install steps except cloning the code.

**Comment by nhomble** [comment]
I think that could work too. That would also keep all the linkage code in a single place. Would it be overkill to wrap all of the `basher-_unlink-*` helpers into one unlink script so that both the uninstall and upgrade scripts could reuse? I only see the `rm` in the actual uninstall script.
