### ISSUE TITLE
Package.yml

### ISSUE THREAD

**Issue by MatusModder** [basherpm/basher#108]
Hi. I have a proposal for you. What about package.yml for quick and easy installation of dependencies. Cuz I want a list of dependencies for my project that includes YAML parsing and I don't want to find the dependencies on Google. Can you make it?

**Comment by pawamoy** [comment]
What do you mean by "quick and easy"? How would changing the format of dependencies from text to YAML make installation of dependencies easier? Bash has no builtin way to parse and load YAML, it doesn't even have nested data structures. What do you mean by "my project that includes YAML parsing"? What do you mean by "find the dependencies on Google"?? 😅 Dependencies are either found on GitHub (repo/project), or other platforms like GitLab. You don't need Google to find them 😕

**Comment by pawamoy** [comment]
Maybe you meant providing a single, big `packages.yml` file that includes all the projects installable through Basher?

**Comment by juanibiapina** [comment]
I also don't understand the proposal.
