### ISSUE TITLE
How to request for a package to be added to https://www.basher.it/package ?

### ISSUE THREAD

**Issue by icasimpan** [basherpm/basher#111]
Hi,

I wrote a simple MVC shell-scripting dev kit and framework and just had the chance to make it fully installable via basher.
I checked the site and this this basher repo and can't find any.

Can you point me into the right direction please?
My package is `github.com/shsdk/shcf`

Thank you.

**Comment by pawamoy** [comment]
I think the repo is here: https://github.com/gitparade-com/basher.it (found it in the news: https://www.basher.it/2020/welcome/)

**Comment by icasimpan** [comment]
Thank you, @pawamoy
