### ISSUE TITLE
Installing a local package

### ISSUE THREAD

**Issue by hinell** [basherpm/basher#113]
Please rename this subsection of README to `Installing a locally developed package`

**Comment by pawamoy** [comment]
What's the reasoning? I find "local package" to be clear enough :thinking:

**Comment by hinell** [comment]
This may be confused for installing into a "local folder of the project", not installing it globally. Thanks!

**Comment by juanibiapina** [comment]
I also think it's clear, specially if you read the rest of the section. Thanks for the idea though 😄
