### ISSUE TITLE
Package Manager

### ISSUE THREAD

**Issue by RennyDem** [basherpm/basher#115]
Dear Dev,

I recently encountered your project. It says that it's a package Manager for bash, but is it possible to convert this to a regular package management system for Linux, if we want to, for let's say a distro?

Best regards,
RennyDemmy

**Comment by juanibiapina** [comment]
Hey, why the question?

**Comment by juanibiapina** [comment]
In that case no, it cannot. It has a completely different use case in mind and no support for compiling packages.

**Comment by RennyDem** [comment]
> In that case no, it cannot. It has a completely different use case in mind and no support for compiling packages.

How about using binary packages?

**Comment by RennyDem** [comment]
I see

**Comment by RennyDem** [comment]
Thanks anyway
