### ISSUE TITLE
Add step for ./configure && make?

### ISSUE THREAD

**Issue by isaacs** [basherpm/basher#13]
Would you be inclined to accept a pr to add `libexec/basher-_build` that would do `./configure` if a configure script is available, and `make` if a Makefile is present?

It would make a lot of programs installable with basher pretty easily, and could be overridden by something in `package.sh` if the user wanted to specify a custom build script.

**Comment by juanibiapina** [comment]
I have conflicting thoughts about this feature. In a way, I like the fact that all packages are restricted to the .basher directory.

With this feature, it would be difficult to control where things are installed. Also, uninstalling becomes a problem. I would like to have a way to solve these problems.

**Comment by juanibiapina** [comment]
@isaacs are there any specific packages that you foresee using this feature?

**Comment by isaacs** [comment]
Yeah, I guess `make` sort of means that you can end up installing things in `/usr/local` or something.  You could set `PREFIX=/path/to/.basher/` but... ugh.  Now we're reinventing autoconf hell.

The specific packages I'd want to use with this are things like https://github.com/nodejs/node or other "binary" command-line platform things.

I completely understand your concern.  It's always a trade-off between flexibility and order.  There are some npm packages that do some questionable things with their `install` scripts.

**Comment by juanibiapina** [comment]
Node is not a shell script, so it is not a target package for basher. Also it is easily found in almost all common package manager like homebrew, apt-get and pacman.

I'm gonna close this for now, but thanks for the contribution!
