### ISSUE TITLE
Allow sources other than github

### ISSUE THREAD

**Issue by binaryphile** [basherpm/basher#21]
I use bitbucket in addition to github and it would be nice to be able to specify that as a source for a particular dependency in DEPS.

Perhaps an optional prepend of source to the DEP, which defaults to github if not specified, a la "bitbucket/my-user/my-package" or somesuch.

**Comment by juanibiapina** [comment]
Great idea. Just like #20 , we should think about allowing this on the `install` command

**Comment by juanibiapina** [comment]
@binaryphile and others: I want to get opinions on this syntax:

```sh
$ basher install user/repo --protocol=ssh --site=github.com
```

Protocol will default to `https` and site to `github.com`. There should also be short options.

**Comment by juanibiapina** [comment]
Another option would be:

```sh
$ basher install --protocol=ssh github.com/user/repo
```

This would allow you to overwrite the protocol when installing, but also allow the site to be specified on the dependencies section of the package.sh. The reasoning here is that you probably never want to specify the protocol when declaring dependencies, and not having the ":" on the package description allows it to be used on the DEPS= variable.

**Comment by juanibiapina** [comment]
I just now realized your original suggestion already had the format a/b/c. So I'll go ahead and merge, closing this issue.

I'll open another issue for ssh access.
