### ISSUE TITLE
Allow ssh protocol

### ISSUE THREAD

**Issue by juanibiapina** [basherpm/basher#25]
As mentioned on #21 , allow users to specify `ssh` protocol when installing. This gives you easy push access if you're developing packages.

A possible syntax would be:

```sh
$ basher install --protocol=ssh user/repo
```
or

```sh
$ basher install --ssh user/repo
```

Protocol would default to https. It should also not affect dependencies, which should always be https.

@binaryphile thoughts?

**Comment by binaryphile** [comment]
That seems like a good syntax to me.
