### ISSUE TITLE
Update zsh completion to compsys

### ISSUE THREAD

**Issue by juanibiapina** [basherpm/basher#31]

**Comment by marvin08** [comment]
I would like to work on this. Can you please elaborate on what needs to be done exactly?

**Comment by juanibiapina** [comment]
@marvin08 sure

Zsh has two completions systems, the old one, compctl and the new one, compsys.

Basher is using the old one here: https://github.com/basherpm/basher/blob/master/completions/basher.zsh

These are the two tasks I can think of:

1 - Convert the completion syntax from one to the other
2 - Figure out how to load the new style completion

The first task is just converting syntax, checking the zsh manual and how it works. The second task requires some investigation: In compctl you would just `source` the completion file, but with compsys, the little I know of, you just put the file somewhere in your zsh fpath for autoloading. I don't know if you can also source the compsys file. If it is possible, there is nothing to do for step 2. If it is not possible (but I don't really think it's the case), we need to figure out how to put the completion file in the correct place.

My experience with zsh completions is not really the best, but I can try to help.

**Comment by marvin08** [comment]
Check if this solves the problem -> #32.
