### ISSUE TITLE
basher run

### ISSUE THREAD

**Issue by pawamoy** [basherpm/basher#41]
I have some scripts that depend on basher being initialized, and I would like to run them in non-terminal places like GUI or Conky.

To do that I had written my own wrapper, but I now think  it could be included in basher as a `run` command.

The `run` command would be written like:

```bash
# get basher install dir
basher_path="$(dirname "$(dirname "$(readlink -e "$0")")")"

# set path
export PATH="${basher_path}/bin:${PATH}"

# init basher
eval "$(basher init - bash)"

# execute given command
"$@"
```

(Note this is written for bash only, I did not consider other shells)

You would typicall call it like
```bash
~/.basher/bin/basher run my_script my_args
```

An example for Conky:
```lua
${execpi 5 ~/.basher/bin/basher run my_script my_args}
```

**Comment by juanibiapina** [comment]
I'm not sure about what the script should actually look like, but I'm not opposed to the idea.

**Comment by pawamoy** [comment]
OK, cool, I'm gonna do some tests locally and send a PR if I get something working.

**Comment by pawamoy** [comment]
I don't think it makes sense anymore. Calling `~/.basher/bin/basher run` is not very practical. Feel free to reopen :slightly_smiling_face:
