### ISSUE TITLE
Handle more cases for basher link

### ISSUE THREAD

**Issue by pawamoy** [basherpm/basher#42]
`basher link` expects the name of a directory *in the current directory*, which is very limited. It means I can't run `basher link .`. I have to go one directory up to use the command, and in some cases it might be possible that I don't even know the directory name. I cannot use an absolute path either (so no `basher link $(pwd)`).

https://github.com/basherpm/basher/blob/09e4641c34b2b3ed007b50e7add7062c9e666f9e/libexec/basher-link#L20

It would be great if basher could handle these two cases: absolute and relative paths (including use of `.` and `..`). It would need to resolve the given argument to an absolute path, then use it's basename when linking, something like

```bash
directory="$(readlink -e "$1")"

ln -s "$directory" "${BASHER_PACKAGES_PATH}/link/$(basename "$directory")"
```

My use case is CI: I end up with the working directory being the project directory. I would like to be able to run `basher link .` or `basher link $(pwd)` before actually running the tests.

**Comment by juanibiapina** [comment]
You're right about all the limitations of the `link` command. I actually wrote it in a bit of a hurry just to test local packages by going up one directory and calling `basher link ...` where the shell would just complete directory names for me.

I like your idea of `basher link $(pwd) shellm/loop`. It seems to be the clearer and safest.

**Comment by pawamoy** [comment]
Cool :slightly_smiling_face: I can try and implement that and send a PR if you want.

**Comment by pawamoy** [comment]
Done in #43, closing!
