### ISSUE TITLE
Shifting options from $@

### ISSUE THREAD

**Issue by pawamoy** [basherpm/basher#48]
I think the code that checks for `--ssh` or `--no-deps` options is wrong.

What I mean is that it works only when the option is the first argument given. If it is second or third, then the wrong argument will be shifted (the first one, not the option).

So instead we should either:
- just check if the first argument is equal to option we look for (no need for a for loop)
- allow the option to be placed elsewhere in the command line with something like:

```bash
args=()
while [ $# -ne 0 ]; do
  case $1 in
    --option) option=true ;;
    *) args+=("$1") ;;
  esac
  shift
done
set -- "${args[@]}"
```

**Comment by juanibiapina** [comment]
I think the first option is simpler and keeps the current behavior. I'm always a bit scared of introducing more code complexity.
