### ISSUE TITLE
"detect shell" test failing on alpine

### ISSUE THREAD

**Issue by pawamoy** [basherpm/basher#50]
Issue again, sorry :grin: !!

There is just a test failing on Alpine/Busybox, the "detect shell" one, because the `ps` command returns nothing (surely different/missing options as well).

I'm talking about Alpine because the official bash docker images are based on it :O https://github.com/tianon/docker-bash

I can try and fix it if you're okay!

**Comment by juanibiapina** [comment]
No need to be sorry! This is great!

I'm ok with busybox support.
