### ISSUE TITLE
Error while running tests on OS X

### ISSUE THREAD

**Issue by kadaan** [basherpm/basher#59]
I keep getting these failures during the basher test run on OS X.  There isn't a lot of info about what the actual error is, what code is being run, etc.

```
 ✓ extracts only usage
 ✓ multiline usage section
 /var/folders/vv/yvb4m22n5f511tbzjjjwcm240000gn/T/bats.44779.src: line 66: syntax error near unexpected token `>'                                                                                                                    51/119
 ✓ multiline extended help section

119 tests, 0 failures

make: *** [test] Error 1
```

**Comment by juanibiapina** [comment]
I have no problems. Maybe different version of `bats` ?

**Comment by kadaan** [comment]
@juanibiapina What version of bats do you have? I have: 
```shell
$ bats --version
Bats 1.1.0```

**Comment by juanibiapina** [comment]
Latest bats version is 0.4.0 before it was hijacked.

**Comment by kadaan** [comment]
@juanibiapina This isn't a bats/bats-core issue.  The issue is [which "$1" &>>/dev/null](https://github.com/basherpm/basher/blob/ce13e8df6b12c6a77d3989d3e5d93cd43adffcad/tests/basher-init.bats#L66) is not backwards compatible with bash 3.x.

**Comment by juanibiapina** [comment]
I don't know if there's any support for bash 3. Not intentional anyway.

**Comment by kadaan** [comment]
@juanibiapina It seems that there should be or an entire platform won't work.
