### ISSUE TITLE
nest package in subfolder

### ISSUE THREAD

**Issue by jasonkuhrt** [basherpm/basher#71]
We would like to keep multiple packages in a single repo (mono-repo). To achieve that we would need `basher` to be able to install from sub-folders of a repo, rather than assuming the whole repo is a single package.

Example:

```
basher install --path <path> <user>/<repo>
```

**Comment by juanibiapina** [comment]
That introduces a lot of complications. Are you sure you want that? I don't think basher is particularly good for that use case.

**Comment by jasonkuhrt** [comment]
Not sure. We decided to not go with a bash package manager for now.
