### ISSUE TITLE
Add some relevant GitHub topics

### ISSUE THREAD

**Issue by dominiksalvet** [basherpm/basher#72]
Hello! It would be awesome to add some relevant GitHub topics to this repository. Is it possible? :rocket:

If you need inspiration, I develop [similar software](https://github.com/dominiksalvet/gitpack), so you can take a look. Or there are others like [bpkg](https://github.com/bpkg/bpkg), from which you can get inspiration as well. :smiley:

**Comment by juanibiapina** [comment]
Check if you like them xD

**Comment by dominiksalvet** [comment]
Great! :smile:
