### ISSUE TITLE
Respect XDG folder specifcations

### ISSUE THREAD

**Issue by taqtiqa-mark** [basherpm/basher#73]
With `XDG_DATA_HOME` set (i..e basher is installed to ~/.local/share/basher)
```bash
basher install shellspec/shellspec
```
created `~/.basher` and installed under that folder.

[Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

Arch Linux has a useful summary of [defaults](https://wiki.archlinux.org/index.php/XDG_Base_Directory)

**Comment by juanibiapina** [comment]
PRs are welcome.
