### ISSUE TITLE
System wide installation - is it possible ?

### ISSUE THREAD

**Issue by grzesuav** [basherpm/basher#86]
Would it be possible to install `basher` system-wide, like via Arch Linux AUR scripts ?

**Comment by juanibiapina** [comment]
would it work if you overwrite `BASHER_ROOT` ?

**Comment by grzesuav** [comment]
hmm I guess partially - as I would like to install `basher` system wide, but would like to install packages in userspace - as otherwise it would require to run basher as root

**Comment by juanibiapina** [comment]
in that case you could use `BASHER_PREFIX` to move the cellar to a user specific location or simply some place where every user has write permissions. Does that work?

**Comment by grzesuav** [comment]
hi. I figured it out to install locally with dotbot, so issue can be closed, at least for me
