### ISSUE TITLE
[Feature Request] Support and maintain patches for popular repos

### ISSUE THREAD

**Issue by cornfeedhobo** [basherpm/basher#87]
After installing [`pyenv`](https://github.com/pyenv/pyenv) I found that it doesn't load the built-in plugin python-build properly. I've submitted a PR upstream, but since I know they can take a long time, it got me thinking about how pyenv itself manages patches for python-build; why not do something similar.

**Comment by juanibiapina** [comment]
Because it's super complicated. I'd rather not go that direction.

**Comment by cornfeedhobo** [comment]
@juanibiapina what do you think about pre/post hooks instead? it'd offer broader support and doesn't require you making patch specific logic.

**Comment by juanibiapina** [comment]
How would that work for patches?

**Comment by cornfeedhobo** [comment]
@juanibiapina I don't envision anyone managing patches in a central way, just simply making it easy for someone to hack locally if the need arises. e.g. when I was working on pyenv, I could have made my a script for my development team to patch after install until my PR was merged upstream.

**Comment by juanibiapina** [comment]
In that case you could also install from your fork, right ? Both things are manual work.

**Comment by cornfeedhobo** [comment]
@juanibiapina yes, I worked around it, but that is very far from the point and maintaining a fork implies a lot more overhead that you are trivializing as compared to maintaining a set of patches that always must be applied for certain software.

I'm sorry, I don't really have an interest trying to explain and justify a very common software pattern. Hooks are useful. I hope you come around on this issue at some point.

**Comment by juanibiapina** [comment]
Let me try to explain it better with a question. Where would you put the code that gets executed in the hook (to fetch and apply the patch, for instance) ?
