### ISSUE TITLE
Avoiding the linking of all executables in the root of a repository

### ISSUE THREAD

**Issue by fidian** [basherpm/basher#9]
I ran `basher install tests-always-included/mo` and then checked out `~/.basher/cellar/bin/` to see what files were linked.  I saw several:

```
lrwxrwxrwx 1 fidian fidian 72 Sep  1 13:53 diagnostic -> /home/fidian/.basher/cellar/packages/tests-always-included/mo/diagnostic*
lrwxrwxrwx 1 fidian fidian 63 Sep  1 13:53 lasher -> /home/fidian/.basher/cellar/packages/basherpm/lasher/bin/lasher*
lrwxrwxrwx 1 fidian fidian 64 Sep  1 13:53 mo -> /home/fidian/.basher/cellar/packages/tests-always-included/mo/mo*
lrwxrwxrwx 1 fidian fidian 73 Sep  1 13:53 run-spec.js -> /home/fidian/.basher/cellar/packages/tests-always-included/mo/run-spec.js*
lrwxrwxrwx 1 fidian fidian 71 Sep  1 13:53 run-tests -> /home/fidian/.basher/cellar/packages/tests-always-included/mo/run-tests*
```

There are several executable programs in tests-always-included/mo and I would like only `mo` to be linked.  Would you consider adding something to `package.sh` that would list the programs that should be linked?

**Comment by juanibiapina** [comment]
You could move it to a bin/ directory, which would make basher link only files in this directory.

I can make the change you requested, but only in a few days. The previous solution already works.

**Comment by juanibiapina** [comment]
@fidian I just added support for a BINS config on package.sh. Still using this?

**Comment by fidian** [comment]
Thanks for getting the commit in to solve this problem.

I am not using basher at the moment, but now this opens up that possibility.
