### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by JerryGreen** [basherpm/basher#92]
After executing this command (using `MINGW64` terminal, which comes with [git](https://git-scm.com/download/win)):

```bash
export PATH="$HOME/.basher/bin:$PATH"
eval "$(basher init - bash)"
```

I get this error:

```bash
/c/Users/Jerry/.basher/bin/basher: line 1: ../libexec/basher: No such file or directory
```

Or if I try to use it:

```bash
$ basher install jerrygreen/git-pr
/c/Users/Jerry/.basher/bin/basher: line 1: ../libexec/basher: No such file or directory
```

It would be cool if it worked on Windows too, so my bash commands would be trasportable, whatever system I use.

**Comment by juanibiapina** [comment]
I don't really do development on windows, so I can't help you with that. I suspect it has something to do with symlinks, but it's just a guess.

Feel free to open a PR if you know a way to fix it that doesn't affect or complicate other systems, but I predict there will be more incompatibilities once this one is fixed.
