### ISSUE TITLE
Feature request: install multiple packages with one command

### ISSUE THREAD

**Issue by NNBnh** [basherpm/basher#96]
Hello, i'm the developer of [SBB (SuperB Bootstrap)](https://github.com/NNBnh/superb-bootstrap) and i would like to add Basher package manager support to [SBB setup script](https://github.com/NNBnh/superb-bootstrap/issues/5). But after looking around, their seem to be no way to install multiple package in one command with Basher like this:

```sh
basher install USER/PACKAGE1 USER/PACKAGE2 USER/PACKAGE3 ...
```

Do i missing something? Help...

**Comment by juanibiapina** [comment]
There is no way currently. It wouldn't be hard to add, but you can also run multiple commands on your side as well.
